### ISSUE TITLE
Progress indicator nav button does not respect (click)

### ISSUE THREAD

**Issue by Blackbaud-AndrewBall** [blackbaud/skyux-progress-indicator#41]
### Expected behavior
Clicking the button should call through to the function bound to (click)
### Actual behavior
The method is not called, and the button vanishes
### Steps to reproduce
This behavior can be seen on the demo page: https://developer.blackbaud.com/skyux/components/wizard
### Severity
Probably high
### Impact
Reasonable amount

**Comment by Blackbaud-SteveBrush** [comment]
The `(click)` event should not be used since form validation needs to be accounted for, before progressing the next step. Instead of using `click`, use `(actionClick)`. This feature hasn't been documented yet, but there's an issue to add it to the docs ASAP. See: https://github.com/blackbaud/skyux2-docs/issues/917.
